[Base]
; Main colors - customize these
text               = f0f0f0
subtext            = a0a0a0
main               = 0a0a0a
sidebar            = 0f0f0f
player             = 0a0a0a
card               = 1a1a1a
shadow             = 000000
selected-row       = 1a1a1a
button             = 1db954
button-active      = 1ed760
button-disabled    = 535353
tab-active         = 1a1a1a
notification       = 1db954
notification-error = e22134
misc               = 535353
